### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by YannickPerret** [tchoune/GPR1-SocialNetwork#1]
@NicolasGlassey 

https://github.com/tchoune/GPR1-SocialNetwork/commit/5dd1dd80a7fce893c1f1a27f969f8a425984a41c Test fonctionnel, sans PSR 12
https://github.com/tchoune/GPR1-SocialNetwork/commit/4a25df041902956c0c9896349950dd3d8c04953d Test fonctionnel. avec PSR12

(C'est le même code)

Il faut utiliser la méthode subscribe dans le constructeur de la classe Twitter

Les variables de la classe Twitter ont été mis à jour pour les standards actuels array() n'est plus recommandé

Il faut envoyer des erreurs lorsque le tableau des observers est vide alors qu'on essaie de supprimer un observer
Si l'utilisateur que l'on souhaite supprimer n'est pas trouvé dans la liste des observers il faut gérer une exception "...NotFound...*

GetTwits n'est pas renseigné correctement j'ai du ajouté la variable dans les propriétés de la classe Twitter.

On vérifie bien que le Subscriber que l'on souhaite ajouté n'est pas déjà dans la liste de la class, sinon on génère une erreur.

Pour le dernier test il n'est pas faisable dans l'état, je ne l'ai donc pas inclus dans cette review

**Comment by NicolasGlassey** [comment]
@tchoune 

Bonjour Yannick,

J'ai pris en compte cette issue pour l'évaluation.

En configurant PSR12 dans mon IDE, de nombreux éléments de votre code ne respectent pas la norme. Etant donné le soin que vous avez apporté à votre issue, je me demande si il n'y aurait pas un problème dans l'application de cette norme.

Exemple:

![image](https://user-images.githubusercontent.com/5616312/202892004-3c00f367-a6d8-44f1-b3d5-5a3fc3a95d2c.png)

Concernant la déclaration des listes, y compris avec la norme activée, il me demande d'ajouter cela:

![image](https://user-images.githubusercontent.com/5616312/202892063-1a713810-f17b-4b1e-b2aa-d45f931e4cbc.png)

Et voilà mon paramètrage dans PhpStorm:

![image](https://user-images.githubusercontent.com/5616312/202892116-27e39279-7324-4089-8bd8-72de3024654c.png)

![image](https://user-images.githubusercontent.com/5616312/202892174-2d2fe51d-b747-4535-81c9-f6c061a9885a.png)


A discuter, bien entendu, ce n'est pas pénalisant pour ce module. Aurions-nous des différences d'application de la norme entre Visual Studio Code et PhpStorm ?

Bonne suite de week-end !
